#!/bin/bash
#
# Alexs .bashrc
# loaded by bash when shell is run
#
# This should only hold 'quick' operations like making sure
# PATH variables and the like are set.
#

# I have stuff in ~/bin
if [ -d $HOME/bin ]; then
  export PATH=~/bin:$PATH
fi

# You would think SHELL is always bash, but not so if we invoke
# bash from a fish shell environment

if [[ -n "$BASH" && "$BASH" != "$SHELL" ]]; then
   export SHELL=$BASH
fi

# locales
#
# It's all a bit of black art to me but if this is what Debian's reconfigure
# can set /etc/default/locale then I guess its good enough for my .bashrc
#
# LC_ALL has precendece over LANG, LC_CTYPE is needed for rxvt-unicode
#

export LC_ALL=en_GB.UTF-8
export LC_CTYPE=en_GB.UTF-8
export LANG=en_GB.UTF-8
export LANGUAGE=en_GB.UTF-8

# Also set some profile parameters to sane values to avoid bleed from
# our full profile
unset PROMPT_COMMAND
