#!/bin/bash
#
# .bashrc_trent
#

SOCRATES_SRC="alex@bennee.com:."
SOCRATES_DST="$HOME/socrates"

SOC_OPTS="-rav --delete-after"

alias sync_socrates="rsync $SOC_OPTS $SOCRATES_SRC $SOCRATES_DST"

# Android SDK
PATH=/home/alex/android-sdk-linux_x86-1.6_r1/tools/:$PATH
