#!/bin/bash
#
# Alexs .bash_profile
# Loaded by bash when any non-login shell started
#
# Normal environment variable tweaks should be hidden away in
# the .bashrc (assuming they don't mess with ssh/tramp stuff)
#

set +x
#
# Source global definitions
#

#echo "Starting ajb's .bashrc $*"
#set -x

#For debuging when we are interactive or non-interactive (tty)
#
#ENVLOG=~/tmp/env`date +%s`.log
#env > $ENVLOG
#echo "ARGS=$*" >> $ENVLOG
#PID=$$
#echo "PID=$PID"  >> $ENVLOG
#cat /proc/$PID/cmdline >> $ENVLOG
#echo "pstree" >> $ENVLOG
#pstree -p >> $ENVLOG

if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

if [ -f /etc/bash.bashrc ]; then
    source /etc/bash.bashrc
fi

#
# Calculate the root directory of this script
#
THIS_SCRIPT="${BASH_SOURCE[0]}"
while [ -h "$THIS_SCRIPT" ]; do
    DIR="$( cd -P "$( dirname "$THIS_SCRIPT" )" && pwd )"
    THIS_SCRIPT="$(readlink "$THIS_SCRIPT")"
    [[ $THIS_SCRIPT != /* ]] && THIS_SCRIPT="$DIR/$THIS_SCRIPT"
done
DOTFILES_DIR=$( cd -P "$( dirname "$THIS_SCRIPT" )" && pwd)

if [ -f $DOTFILES_DIR/dotbashrc ]; then
    source $DOTFILES_DIR/dotbashrc
fi

#############
# Aliases
#############

# I like a quick grep of history
alias h="history | grep"

# Find a given export in history
function he
{
    if [ "$1" ]
    then
       history | grep -E "^ [0-9]+  export $1" | uniq -s 6 -u
    fi
}

# Search through a list of alternative binaries, returning the first match
function find_alternatives ()
{
    for arg in "$@"
    do
      # --skip-alias only works with GNU which
      # file=`which --skip-alias $arg 2> /dev/null`
      file=`which $arg 2> /dev/null`
      if [ -x "$file" ]; then
	  echo "$file"
	  return
      fi
    done
    echo "/alternative/not/found"
}

# Search though a list of directories, returning first match
function find_directories ()
{
    for d in "$@"
    do
      if [ -d "$d" ]; then
	  echo "$d"
	  return
      fi
    done
    echo "/alternative/not/found"
}

#
# Lets see if we have a decent "grep"
#
GREP=$(find_alternatives "ack-grep" "ggrep" "grep" "/bin/grep")
alias grep="$GREP"

#
# Look for a decent diff
#
DIFF=$(find_alternatives "gdiff" "diff")
alias diff="$DIFF"

#
# Some systems I use don't have a decent 'find' implentation so
#

# Lets look for gfind first (The GNU find on Solaris)
FIND=$(find_alternatives "gfind" "find")
alias find="$FIND"

FIND_VERSION=`find --version 2>/dev/null`
if [  "${FIND_VERSION:0:8}" == "GNU find" ]; then

    # Some nice find expressions
    FIND_BACKUPS=" -name '.#*' -o -name '#*#' -o -name '*\.~*.~' -o -path '*./CVS/*.'"
    FIND_CVS=" -path '*./CVS/.*' "
    FIND_CCODE="  -iname '*.[chS]' -or -iname '*.cc' "
    FIND_CHEAD=" -iname '*.h' "
        
    # and search code for stuff (when I figure out proper expansion and quuting I'll make this neater)
    
    #alias sc="find . -iname '*.[chS]' -or -iname '*.cc' -and -not \( -name '.#' -o -name '#*#' -o -name '*\.~*.~' -o -path '*./CVS/*.' \) -print0 | xargs -0 grep -H "

    alias f="$FIND -iname"
    alias sc="$FIND . \( $FIND_CCODE \) -and -not \( $FIND_BACKUPS -o $FIND_CVS \) -print0 | xargs -0 grep -H"
#    alias sh="find . -iname '*.h' -print0 | xargs -0 grep -H "
    alias sa="$FIND . -xtype f -print0 | xargs -0 grep -H "
else
    #
    # Who knows how standard unix is, its not GNU so probably not
    #
    # Lets assume both find and grep are borken
    #

    # Find files under here
    alias f="$FIND . -name"

    # and search code for stuff
    alias sc="$FIND . -name '*.[chS]' -o  -name '*.cc' | xargs grep "
#    alias sh="find . -name '*.h' | xargs grep "
    alias sa="$FIND -L . -type f | xargs grep "
fi    

# Find a decent browser
BROWSER=$(find_alternatives "chromium-browser" "google-chrome" "chrome" "firefox-4.0" "firefox" "mozilla")

######################
# Environent Variables
######################

# One editor
export EDITOR=emacs

# set CFLAGS for debugging - autoconf usually picks it up.
#export CFLAGS=-g3

# CVS exports
export CVS_RSH=ssh
export CVSEDITOR=ec

# Setup history control - hard to get right, could do with
# bashcompletion as well. Just make sure I don't repeatedly delete stuff
# See: http://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows#3055135

# append (as I use lots of shells)
shopt -s histappend

export HISTCONTROL=ignoredups:erasedups
#export HISTIGNORE="rm *"
export HISTIGNORE="&:rm *ls:[bf]g:exit"
export HISTSIZE=100000
export HISTFILESIZE=${HISTSIZE}

history() {
  _bash_history_sync
  builtin history "$@"
}

_bash_history_sync() {
  builtin history -a         #1
  HISTFILESIZE=$HISTSIZE     #2
  builtin history -c         #3
  builtin history -r         #4
}

# fixup 
export PROMPT_COMMAND=_bash_history_sync

# GNU systems usually use less by default for
# man pages, however not all unix-a-likes do
export PAGER=less


#
# surfraw, command line browser control
# http://surfraw.alioth.debian.org/
#
SURFRAW=$(find_alternatives "surfraw")
if [[ -f $SURFRAW ]]; then
    alias wiki="$SURFRAW wikipedia "
    alias google="$SURFRAW google "
    alias imdb="$SURFRAW imdb "
    alias code="$SURFRAW codesearch"
    alias jspcode="$SURFRAW codesearch lang:jsp"
    alias javacode="$SURFRAW codesearch lang:java"
    alias pycode="$SURFRAW codesearch lang:python"
fi

########################
# Miscelaneous Stuff
########################
# I want core-dumps dammit
ulimit -S -c unlimited


# Helper function to load extra bits of profile that
# are optional depending on the environment.
LOADED_MODULES=""
function load_extra_module()
{
    module=$1
    shift

    find_exes=$(find_alternatives $*)
    module_path=${DOTFILES_DIR}/dotbash_${module}
    if [[ -f $find_exes && -f $module_path ]]; then
        source $module_path
        LOADED_MODULES="$LOADED_MODULES $module"
    fi
}

# If invoked as /bin/sh let's assume a minimal environment
if [ "$SHELL" == "/bin/sh" ]; then
    echo "Executing $SHELL under minmal environment"
else
    load_extra_module ps1 true
    load_extra_module path true
    load_extra_module tmux tmux
    load_extra_module emacs emacs
    load_extra_module git git
    load_extra_module apt apt-get
    load_extra_module kvm kvm
    load_extra_module keys ssh-agent gpg-agent keychain
    load_extra_module screen screen
    load_extra_module valgrind valgrind
    load_extra_module bitbake bitbake
    load_extra_module ccache ccache

    # Gentoo is special...
    if [[ `whoami` != "root" ]]; then
        load_extra_module gentoo emerge
    else
        unset CFLAGS
    fi

    load_extra_module `hostname` true
    load_extra_module devqemu true
    
    load_extra_module user true
    load_extra_module local true
    echo "Loaded$LOADED_MODULES"
fi

clean_path

# Alias for reloading
alias .profile=". ~/.bash_profile"
