#!/bin/bash
#
# .bashrc_trent
#

SOCRATES_SRC="alex@bennee.com:."
SOCRATES_DST="$HOME/socrates"

SOC_OPTS="-rav --delete-after"

alias sync_socrates="rsync $SOC_OPTS $SOCRATES_SRC $SOCRATES_DST"

# Android SDK
PATH=/home/alex/android-sdk-linux_86/tools/:$PATH

# Disable touchpad while typing
# GUI session
#syndaemon -i 2 -d -K

# AutoSSH
#alias start_backchan="autossh -2 -fN -M 20000 -R 10001:localhost:22 alex@bennee.com"
alias start_backchan="autossh -2 -fN -R 10001:localhost:22 alex@bennee.com"

