#!/bin/bash
#
# Gentoo Related Bash Functions
#
# These are various tools for manipulating a local
# portage structure (which can be part of an overlay)
#
# These functions allow you to list, clone, delete and diff ebuilds
#

if [ -d /usr/portage ];
then
  LOCAL_PORTAGE=$HOME/src/gentoo/portage
  MASTER_PORTAGE=/usr/portage

  export PORTAGE_TMPDIR=$HOME/src/gentoo/tmp 

  alias ls_le="find $LOCAL_PORTAGE -mindepth 2 -maxdepth 2 -xtype d -and -not -path \"*/.git*\" | sed s#$LOCAL_PORTAGE##"
  alias ls_me="find $MASTER_PORTAGE -mindepth 2 -maxdepth 2 -xtype d  | sed s#$MASTER_PORTAGE##"
fi
  
#
# guess_ebuild
#
# Take a string, possibly partial and match it a proper group/ebuild
#
function guess_ebuild()
{
    n=`ls_me | grep $1 | wc -l`
    tmp=`ls_me | grep $1`
    if [ "$n" == "1" ]; then
	group=`echo $tmp | perl -ne 'm#/([^/]*)#; print "$1"'`
	ebuild=`echo $tmp | perl -ne 'm#/([^/]*)/(.*)$#; print "$2"'`
	echo "guess_ebuild: $group/$ebuild"
    else
	unset group
	unset ebuild
	echo "guess_ebuild: not unique enough"
	echo $tmp
    fi
}


#
# diff ebuild
#
# Do a diff for a given ebuild
#
function diff_ebuild()
{
    result=0
    
    if [ "$1" ]
    then
	guess_ebuild $1
	if [[ "$group" && "$ebuild" ]]
	then
	    if [ -d $MASTER_PORTAGE/$group/$ebuild ]; then
		diff -ub $MASTER_PORTAGE/$group/$ebuild $LOCAL_PORTAGE/$group/$ebuild
	    else
		echo "$group/$ebuild not in master portage"
	    fi
	fi
    else
	for ebuild in `ls_le`
	do
	    if [ -d $MASTER_PORTAGE/$ebuild ]; then
		diff -ub $MASTER_PORTAGE/$ebuild $LOCAL_PORTAGE/$ebuild
	    else
		echo "$ebuild not in master portage"
	    fi
	done
    fi
}

#
# Clone an ebuild from the master tree into the local tree
#
#
function clone_ebuild()
{
    if [ "$1" ]
    then
	guess_ebuild $1
	if [[ "$group" && "$ebuild" ]]
	then 
	    echo "Cloning ebuild $group/$ebuild"
	    mkdir -p $LOCAL_PORTAGE/$group
	    cp -aP $MASTER_PORTAGE/$group/$ebuild $LOCAL_PORTAGE/$group/
	else
	    echo "$1 not in  Master Portage"
	fi
    else
        echo "No ebuild specified"
    fi
}

#
# Sync Ebuild
#
# Bring changes from maintree into local portage
#
function sync_ebuild()
{
    old_cwd=`pwd`
    
    if [ "$1" ]
    then
	guess_ebuild $1
	if [[ "$group" && "$ebuild" ]]
	then 
	    echo "Syncing ebuild $group/$ebuild"
	    cd $LOCAL_PORTAGE
	    rsync --ignore-existing -r /usr/portage/${group}/${ebuild}/ ${group}/${ebuild}/
	    git status
	fi
    else
        echo "No ebuild specified"
    fi

    cd $old_cwd
}



#
# Clean ebuilds
#
# Delete untouched ebuilds from local portage
#
function clean_ebuilds()
{
    for ebuild in `ls_le`
    do
      if [ -d $MASTER_PORTAGE/$ebuild ]; then
	  result=`diff -br --brief $MASTER_PORTAGE/$ebuild $LOCAL_PORTAGE/$ebuild`
	  if [ "x$result" == "x" ]
	  then
	      echo "Removing local copy of $ebuild"
	      rm -rf $LOCAL_PORTAGE/$ebuild
	  fi
      else
	  echo "$ebuild does not exist in master portage"
      fi
    done
}
