#!/bin/bash
#
# Alexs .bash configuration
#
# tmux configuration

TMUX_SESSIONS=0
TMUX_WINDOWS=0

TMUX_SESSIONS=`tmux list-sessions | wc -l`
TMUX_WINDOWS=`tmux list-windows | wc -l`

if [[ `whoami` == "root" ]]; then
    function sysmon()
    {
	if ! tmux has-session -t system; then
	    tmux new-session -d -s system
 	    tmux new-window -t system -n 'htop' 'htop'
 	    tmux new-window -t system -n 'iotop' 'iotop -P -o -d 30'
 	    tmux new-window -t system -n 'powertop' 'powertop'
	fi
	tmux attach-session -t system
    }
fi

# From: http://brainscraps.wikia.com/wiki/Renumbering_tmux_Windows
function tmux_renumber
{
    for session in $(tmux ls | awk -F: '{print $1}') ;do
	active_window=$(tmux lsw -t ${session} | awk -F: '/\(active\)$/ {print $1}')
	inum=0
	for window in $(tmux lsw -t ${session} | awk -F: '{print $1}') ;do
	    if [ ${window} -gt ${inum} ] ;then
		echo "${session}:${window} -> ${session}:${inum}"
		tmux movew -d -s ${session}:${window} -t ${session}:${inum}
	    fi
	    if [ ${window} = ${active_window} ] ;then
		new_active_window=${inum}
	    fi
	    inum=$((${inum}+1))
	done
	tmux select-window -t ${session}:${new_active_window}
    done
}

alias tn="tmux new-session -s "
alias ta="tmux attach-session -t "

echo "loading .bash_tmux ($TMUX_SESSIONS sessions, $TMUX_WINDOWS windows)"
export USING_TMUX=1
