#!/bin/bash
#
# .bashrc_zen
#
# Local work related changes
#

# Override Author
export GIT_AUTHOR_EMAIL="alex.bennee@linaro.org"

MY_USER=`id -u`
MY_GRP=`id -g`
USERSPEC="--userspec ${MY_USER}:${MY_GRP}"

# General paramters
QEMU_SRC=/home/alex/lsrc/qemu/qemu.git
QEMU_ARCH=aarch64
QEMU_BUILD=${QEMU_SRC}/${QEMU_ARCH}-linux-user
QEMU_BIN=qemu-${QEMU_ARCH}
QEMU_LOGFILE=/tmp/qemu.log

# Root of all rootfs
ROOT_ROOTFS=/home/alex/lsrc/qemu/rootfs

QEMU_ARGS="-d unimp"
# unimp,int,exec,cpu,op,out_asm
QEMU_PROFILE=""

: ${CURRENT_ROOTFS:=${ROOT_ROOTFS}/opensuse-arm64-rootfs}


function run_static_qemu
{
    date > ${QEMU_LOGFILE}

    echo "Copying ${QEMU_BUILD}/${QEMU_BIN} to ${CURRENT_ROOTFS}/bin/" | tee -a ${QEMU_LOGFILE}
    sudo cp ${QEMU_BUILD}/${QEMU_BIN} ${CURRENT_ROOTFS}/bin/
    CMD="/bin/${QEMU_BIN} -D ${QEMU_LOGFILE} ${QEMU_ARGS}"
    echo "Using chroot: ${CURRENT_ROOTFS}" | tee -a ${QEMU_LOGFILE}
    echo "Running: ${CMD} with $# args ($@)" | tee -a ${QEMU_LOGFILE}
    sudo ${QEMU_PROFILE} chroot ${USERSPEC} ${CURRENT_ROOTFS} ${CMD} "$@"
}

function run_static_qemu_as_root
{
    date > ${QEMU_LOGFILE}

    echo "Copying ${QEMU_BUILD}/${QEMU_BIN} to ${CURRENT_ROOTFS}/bin/" | tee -a ${QEMU_LOGFILE}
    sudo cp ${QEMU_BUILD}/${QEMU_BIN} ${CURRENT_ROOTFS}/bin/
    CMD="/bin/${QEMU_BIN} -D ${QEMU_LOGFILE} ${QEMU_ARGS}"
    echo "Using chroot: ${CURRENT_ROOTFS}" | tee -a ${QEMU_LOGFILE}
    echo "Running: ${CMD} with $# args ($@)" | tee -a ${QEMU_LOGFILE}
    ${QEMU_PROFILE} sudo chroot ${CURRENT_ROOTFS} ${CMD} "$@"
}


function set_dynamic_qemu_args
{
    export QEMU_LD_PREFIX=${ROOT_ROOTFS}/${CURRENT_ROOTFS}
    echo "Using QEMU_LD_PREFIX=${QEMU_LD_PREFIX}"
}

function set_qemu_profile
{
    OLD_QEMU_PROFILE=${QEMU_PROFILE}
    QEMU_PROFILE="$@"
    echo "Using QEMU_PROFILE=${QEMU_PROFILE} (was ${OLD_QEMU_PROFILE})"
}

function set_qemu_args
{
    OLD_QEMU_ARGS=${QEMU_ARGS}
    QEMU_ARGS=$@
    echo "Set args to ${QEMU_ARGS} (were ${OLD_QEMU_ARGS})"
}

function set_qemu_rootfs
{
    OLD_QEMU_ROOTFS=${CURRENT_ROOTFS}
    CURRENT_PWD=`pwd`
    cd ${ROOT_ROOTFS}
    DIRS=`compgen -d`
    read -e -p "dir:" NEW_ROOTFS
    CURRENT_ROOTFS=${ROOT_ROOTFS}/${NEW_ROOTFS}
    echo "Set rootfs to ${CURRENT_ROOTFS} (was ${OLD_QEMU_ROOTFS})"
    cd -
}

function setup_rootfs_mounts
{
    # TODO, protect against multiple mounts
    echo "Ensuring mounts in place"
    sudo mount -o bind /home ${CURRENT_ROOTFS}/home
    mkdir -p ${CURRENT_ROOTFS}/root/risu
    sudo mount -o bind /home/alex/lsrc/qemu/risu.git ${CURRENT_ROOTFS}/root/risu/
    mkdir -p {$CURRENT_ROOTFS}/host-etc
    sudo mount -o bind /etc ${CURRENT_ROOTFS}/host-etc
    mkdir -p {$CURRENT_ROOTFS}/host-proc
    sudo mount -o bind /proc ${CURRENT_ROOTFS}/host-proc
    sudo mount -o bind /dev/pts ${CURRENT_ROOTFS}/dev/pts
    sudo mount -o bind /tmp ${CURRENT_ROOTFS}/tmp
}

function kill_qemu
{
    QEMU_PID_CMD="ps -o comm,pid -C $QEMU_BIN | awk '\$1 == \"$QEMU_BIN\" { print \$2 }'"
    echo "QEMU_PID_CMD=${QEMU_PID_CMD}"
    QEMU_PID=`${QEMU_PID_CMD}`
    echo "kill -9 $QEMU_PID"
}


alias .zen=". ~/.bash_zen"
