#!/bin/bash
#
# Alexs .bashrc_apt
#
# Stuff useful when running on apt based systems

#
# Debian Stuff
#
export DEBFULLNAME='Alex Bennée'
export DEBEMAIL='alex@bennee.com'
# This is typically set by "local" configs
export DEBKEYID=''

alias acs="apt-cache search"

# A simple wrapper for dpkg-buildpackage
function dpkg-build
{
    # Sanity
    if [ -d `pwd`/debian ]; then
	CMD="dpkg-buildpackage -tc -rfakeroot"
	if [ "${DEBKEYID}" != "" ]; then
	    CMD="${CMD} -k${DEBKEYID}"
	fi
	echo "Running $CMD";
	$CMD
    else
	echo "Not in a Debian source tree"
    fi
}

# Same again for git-buildpackage
function git-build
{
    # Sanity
    if [ -d `pwd`/debian ]; then
	CMD="git-buildpackage -sa -tc -rfakeroot"
	if [ "${DEBKEYID}" != "" ]; then
	    CMD="${CMD} -k${DEBKEYID}"
	fi
	echo "Running $CMD";
	$CMD
    else
	echo "Not in a Debian source tree"
    fi
}
