#!/bin/bash
#
# .bashrc_ccache
#
# ccache specific tweaks
#

export CCACHE_DIR="/tmp/${USER}/ccache"
mkdir -p ${CCACHE_DIR}

if [ -d /usr/lib/ccache ]; then
    export PATH=/usr/lib/ccache:$PATH
fi 

# for the benefit of Android
export USE_CCACHE=1

#
# Remove ccache from the environment
#
function rmccache
{
    PATH=$(echo "$PATH" | awk -v RS=: -v ORS=: '$1 != "/usr/lib/ccache" {print $1}')
    unset USE_CCACHE
}

alias .ccache=". ~/.bash_ccache"
echo "loading .bash_ccache (using ${CCACHE_DIR})"
