#!/bin/bash
#
# Specific Setups for Danny
#

#
# Sync IPOD
#
MUSIC_ROOT=$HOME/music/
IPOD_ROOT=/media/iPod/music/

alias sync_ipod="rsync -rP --size-only $MUSIC_ROOT $IPOD_ROOT"

#
# Sync Torrents
#

function sync_torrents
{
    cd /home/alex/Downloads/bittorrent
    rsync -rP alex@bennee.com:torrent/* .
}

#
# Push files to NAS
#
function copy_to_nas
{
    scp $* admin@nas:/volume1/video/
}

#
# Rockbox compiler
#
export PATH=$PATH:/home/alex/src/rockbox/tools/bin

# Backchannel
alias start_backchan="autossh -2 -fN -M 0 -R 10000:localhost:22 alex@bennee.com"

# Reload
alias .danny=". ~/.bash_danny"

